# Basic Information 
title: Mohamed Elmoghany
#position: Research Intern @ KAUST
affiliation: KAUST Research Internship
affiliation_link: https://vision-cair.kaust.edu.sa/computer-vision-core-ai-research-group
#affiliation_logo: ./assets/logo/logo.png
email: m.osama.elmoghany@gmail.com

# Search Engine Optimization (SEO)
keywords: Mohamed Elmoghany, Elmoghany, generative AI, curawella, cammedar, kaust, sjsu, llm, vlm, diffusion
canonical: https://elmoghany.github.io
description: Mohamed Elmoghany is a machine learning researcher with interests in generative AI, image and video generation, LLMs optmization, machine learning theoritical and architectural development.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=W7-8dq4AAAAJ
github_link: https://github.com/elmoghany/
#linkedin: https://www.linkedin.com/in/elmoghany/
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: assets/profile/profile.jpg

# Footnotes
footnote: (updated Mar'25) create your website using this template
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
